// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: ef2331b7e2
// Version Date: 2020-10-07T23:22:38Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "todo"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TodoServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.TodoServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// todo

		additem: grpctransport.NewServer(
			endpoints.AddItemEndpoint,
			DecodeGRPCAddItemRequest,
			EncodeGRPCAddItemResponse,
			serverOptions...,
		),
		deleteitem: grpctransport.NewServer(
			endpoints.DeleteItemEndpoint,
			DecodeGRPCDeleteItemRequest,
			EncodeGRPCDeleteItemResponse,
			serverOptions...,
		),
		listall: grpctransport.NewServer(
			endpoints.ListAllEndpoint,
			DecodeGRPCListAllRequest,
			EncodeGRPCListAllResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TodoServer interface
type grpcServer struct {
	additem    grpctransport.Handler
	deleteitem grpctransport.Handler
	listall    grpctransport.Handler
}

// Methods for grpcServer to implement TodoServer interface

func (s *grpcServer) AddItem(ctx context.Context, req *pb.AddItemRequest) (*pb.ItemResponse, error) {
	_, rep, err := s.additem.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ItemResponse), nil
}

func (s *grpcServer) DeleteItem(ctx context.Context, req *pb.DeleteItemRequest) (*pb.ItemResponse, error) {
	_, rep, err := s.deleteitem.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ItemResponse), nil
}

func (s *grpcServer) ListAll(ctx context.Context, req *pb.EmptyRequest) (*pb.ListResponse, error) {
	_, rep, err := s.listall.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListResponse), nil
}

// Server Decode

// DecodeGRPCAddItemRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC additem request to a user-domain additem request. Primarily useful in a server.
func DecodeGRPCAddItemRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.AddItemRequest)
	return req, nil
}

// DecodeGRPCDeleteItemRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC deleteitem request to a user-domain deleteitem request. Primarily useful in a server.
func DecodeGRPCDeleteItemRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.DeleteItemRequest)
	return req, nil
}

// DecodeGRPCListAllRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC listall request to a user-domain listall request. Primarily useful in a server.
func DecodeGRPCListAllRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.EmptyRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCAddItemResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain additem response to a gRPC additem reply. Primarily useful in a server.
func EncodeGRPCAddItemResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ItemResponse)
	return resp, nil
}

// EncodeGRPCDeleteItemResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain deleteitem response to a gRPC deleteitem reply. Primarily useful in a server.
func EncodeGRPCDeleteItemResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ItemResponse)
	return resp, nil
}

// EncodeGRPCListAllResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain listall response to a gRPC listall reply. Primarily useful in a server.
func EncodeGRPCListAllResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
